dist: bionic
language: go
go:
  - '1.15'

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      script:
        - go get -u github.com/gobuffalo/packr/packr
        - CGO_ENABLED=1 GOOS=linux GOARCH=amd64 $GOPATH/bin/packr build -a -tags netgo -ldflags '-w -extldflags "-static"' -o npviz cmd/main.go
      deploy:
        provider: releases
        api_key: "${GITHUB_PERSONAL_TOKEN}"
        file:
        - "npviz"
        skip_cleanup: true
        on:
          tags: true
